# Generated by Django 4.2.18 on 2025-01-16 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.UUIDField(db_index=True)),
                ("key", models.CharField(db_index=True, max_length=255)),
                ("value", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("str", "String"),
                            ("int", "Integer"),
                            ("float", "Float"),
                            ("bool", "Boolean"),
                            ("datetime", "DateTime"),
                            ("json", "JSON"),
                        ],
                        db_index=True,
                        default="str",
                        max_length=20,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property",
                "verbose_name_plural": "Properties",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="properties__content_b7fbc8_idx",
                    ),
                    models.Index(fields=["key"], name="properties__key_0c9cd5_idx"),
                    models.Index(
                        fields=["created"], name="properties__created_416cb9_idx"
                    ),
                ],
                "unique_together": {("content_type", "object_id", "key")},
            },
        ),
    ]
