version: '3.8'

services:
  web:
    build: ./docrepo
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./docrepo/:/usr/src/docrepo/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      # - elasticsearch
      - db
      # - minio
  db:
    image: postgres:16
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=docrepo
    ports:
        - "6543:5432"
  
  ### Uncomment the following to use Keycloak (kcdb and keycloak services)
  ### kcdb is the database used by Keycloak
  # kcdb:
  #     image: postgres
  #     volumes:
  #       - dev_postgres_data_kc:/var/lib/postgresql/data
  #     environment:
  #       POSTGRES_DB: keycloak
  #       POSTGRES_USER: keycloak
  #       POSTGRES_PASSWORD: password
  #       POSTGRES_PORT: 5432
  #     ports:
  #       - "8764:5432"
  # keycloak:
  #     image: quay.io/keycloak/keycloak:26.0.1  # Can use legacy, latest or version number
  #     # volumes:
  #      # - ./imports:/opt/jboss/keycloak/imports
  #     environment:
  #       DB_VENDOR: POSTGRES
  #       DB_ADDR: kcdb
  #       DB_DATABASE: keycloak
  #       DB_USER: keycloak
  #       DB_SCHEMA: public
  #       DB_PASSWORD: password
  #       KEYCLOAK_USER: admin
  #       KEYCLOAK_PASSWORD: admin
  #       KEYCLOAK_ADMIN: admin 
  #       KEYCLOAK_ADMIN_PASSWORD: admin
  #       # KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled
  #       KEYCLOAK_FRONTEND_URL: http://keycloak:8080/auth
  #       KC_LOG_LEVEL: INFO
  #       # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
  #       #JDBC_PARAMS: "ssl=true"
  #     command: 
  #       - start-dev # for :latest
  #     ports:
  #       - 8080:8080
  #     depends_on:
  #       - kcdb

  ### Uncomment the following to use Minio
  # minio:
  #   # See https://hub.docker.com/r/minio/minio/tags
  #   image: quay.io/minio/minio:RELEASE.2024-07-16T23-46-41Z.fips
  #   environment:
  #     - MINIO_ROOT_USER=admin
  #     - MINIO_ROOT_PASSWORD=adminpass
  #   entrypoint: /bin/bash
  #   command: -c 'minio server /data --console-address ":9001"'
  #   volumes:
  #     - miniodata:/data
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"

  # Elastic Search
  # elasticsearch:
  #   image: elasticsearch:8.15.1
  #   volumes:
  #     - es_data:/usr/share/elasticsearch/data
  #   ports:
  #     - 9200:9200
  #     - 9300:9300
  #   environment:
  #     - discovery.type=single-node
  #     - xpack.security.enabled=false

volumes:
  dev_postgres_data:
  ### Uncomment to use Keycloak:
  # dev_postgres_data_kc:
  ### Uncomment to use Elastic
  # es_data:
  ### Uncomment the following to use Minio
  # miniodata:
  #   driver: local
