# Generated by Django 4.2.18 on 2025-02-22 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("repo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ("-created",),
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
            },
        ),
        migrations.AlterModelOptions(
            name="folder",
            options={
                "ordering": ("-created",),
                "verbose_name": "Folder",
                "verbose_name_plural": "Folders",
            },
        ),
    ]
