# Generated by Django 4.2.20 on 2025-03-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repo", "0002_alter_document_options_alter_folder_options"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["name"], name="repo_docume_name_daecbe_idx"),
        ),
        migrations.AddIndex(
            model_name="folder",
            index=models.Index(fields=["name"], name="repo_folder_name_502f64_idx"),
        ),
        migrations.AddIndex(
            model_name="mimetype",
            index=models.Index(fields=["name"], name="repo_mimety_name_2f0727_idx"),
        ),
        migrations.AddIndex(
            model_name="mimetype",
            index=models.Index(
                fields=["extension_list"], name="repo_mimety_extensi_33b58b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["user"], name="repo_profil_user_id_96077d_idx"),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["home_folder"], name="repo_profil_home_fo_ed2b16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="version",
            index=models.Index(
                fields=["parent"], name="repo_versio_parent__485157_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="version",
            index=models.Index(fields=["tag"], name="repo_versio_tag_c60b6f_idx"),
        ),
        migrations.AddIndex(
            model_name="version",
            index=models.Index(
                fields=["content_file"], name="repo_versio_content_ac7d99_idx"
            ),
        ),
    ]
