# Generated by Django 4.2.16 on 2024-12-04 14:53

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from ..test_projects.setup import setup_test_projects


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("repo", "0001_initial"),
        ("comments", "0002_alter_comment_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("etags", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("managed", "Managed"),
                            ("private", "Private"),
                        ],
                        default="public",
                        max_length=30,
                    ),
                ),
                (
                    "managers_group",
                    models.CharField(blank=True, max_length=355, null=True),
                ),
                (
                    "editors_group",
                    models.CharField(blank=True, max_length=355, null=True),
                ),
                (
                    "readers_group",
                    models.CharField(blank=True, max_length=355, null=True),
                ),
                ("comments", models.ManyToManyField(blank=True, to="comments.comment")),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="repo.folder",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="etags.tag")),
            ],
            options={
                "ordering": ["-created"],
                "unique_together": {
                    ("name", "readers_group"),
                    ("name", "managers_group"),
                    ("name", "editors_group"),
                },
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["folder"], name="projects_pr_folder__d1dcdf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["created"], name="projects_pr_created_3ef374_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["visibility"], name="projects_pr_visibil_b48d7f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["is_active"], name="projects_pr_is_acti_f7dee7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["managers_group"], name="projects_pr_manager_f704d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["editors_group"], name="projects_pr_editors_5cc031_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["readers_group"], name="projects_pr_readers_591e82_idx"
            ),
        ),
        migrations.RunPython(setup_test_projects),
    ]
