# Generated by Django 4.2.18 on 2025-01-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="project",
            name="projects_pr_visibil_b48d7f_idx",
        ),
        migrations.RemoveIndex(
            model_name="project",
            name="projects_pr_is_acti_f7dee7_idx",
        ),
        migrations.RemoveIndex(
            model_name="project",
            name="projects_pr_manager_f704d4_idx",
        ),
        migrations.RemoveIndex(
            model_name="project",
            name="projects_pr_editors_5cc031_idx",
        ),
        migrations.RemoveIndex(
            model_name="project",
            name="projects_pr_readers_591e82_idx",
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["visibility", "is_active"],
                name="projects_pr_visibil_6acf65_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["managers_group", "is_active"],
                name="projects_pr_manager_6ad25e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["editors_group", "is_active"],
                name="projects_pr_editors_949d9d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["readers_group", "is_active"],
                name="projects_pr_readers_3f3d6f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["owner"], name="projects_pr_owner_i_dea3a1_idx"),
        ),
    ]
