# Generated by Django 4.2.20 on 2025-03-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_remove_project_projects_pr_visibil_b48d7f_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["name", "is_active"], name="projects_pr_name_855d76_idx"
            ),
        ),
    ]
