# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "tz_detect",
    "widget_tweaks",
    "apps.ddocs",
    "apps.core",
    "apps.dashlets",
    "apps.bookmarks",
    "apps.transformations",
    "apps.repo",
    "apps.ui",
    "apps.authentication",
    "apps.projects",
    "apps.clipboard",
    "apps.search",
    "apps.etags",
    "apps.comments",
    "apps.comms",
    "debug_toolbar",
]
