# Generated by Django 4.2.20 on 2025-03-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transformations", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="preview",
            index=models.Index(
                fields=["version"], name="transformat_version_262538_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="preview",
            index=models.Index(
                fields=["content_file"], name="transformat_content_4e360a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="preview",
            index=models.Index(
                fields=["created"], name="transformat_created_3fa4af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="preview",
            index=models.Index(
                fields=["modified"], name="transformat_modifie_c257d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="thumbnail",
            index=models.Index(
                fields=["version"], name="transformat_version_0bffb6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="thumbnail",
            index=models.Index(
                fields=["content_file"], name="transformat_content_8f0490_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="thumbnail",
            index=models.Index(
                fields=["created"], name="transformat_created_d69b85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="thumbnail",
            index=models.Index(
                fields=["modified"], name="transformat_modifie_fb51bb_idx"
            ),
        ),
    ]
